/* Multi-question applied checks for completed depth-edition modules. */
window.SALES_MASTERY.assessments={
'32':[
{prompt:'A prospect shows strong web intent but requires a deployment model you cannot support. What is strongest?',options:['Fast-track the opportunity because intent is high','Clarify whether the requirement is mandatory and disqualify if it is','Offer a discount to offset the limitation'],answer:1,explanation:'Intent does not repair poor fit. Clarification and, when necessary, disqualification protect both parties. A supported alternative or a changed requirement could alter the decision.'},
{prompt:'Two groups report the same problem, but one self-serves and the other requires a six-month security process. What should you do?',options:['Keep one segment because the problem is identical','Model them separately because buying process and cost to serve differ','Choose the faster group without further evidence'],answer:1,explanation:'Segments should predict different decisions. Combining them hides motion, proof, and economic differences; speed alone may ignore greater durable value. Retention, margin, and reachable demand could change priority.'},
{prompt:'Buyers praise a differentiator but rarely use it after purchase. What is strongest?',options:['Keep leading with it because interviews were positive','Downgrade the claim until behavior or outcome evidence supports it','Remove the feature immediately'],answer:1,explanation:'Praise is weak evidence of realized value. Downgrading the claim preserves uncertainty without overreacting. If the feature works passively, a better outcome measure could restore the claim.'},
{prompt:'One proposed ICP has high win rate but poor retention. Is it proven?',options:['Yes, acquisition proves fit','No; investigate selection, implementation, margin, and realized value','Yes, if sales cycles are short'],answer:1,explanation:'Win rate measures acquisition, not durable fit. Cohort retention, time-to-value, margin, and causal evidence may support or reject the segment.'}
],
'33':[
{prompt:'A buyer reports a serious problem but has not measured it or assigned an owner. What is strongest?',options:['Push for a decision while concern is high','Propose a small diagnostic action and keep it unqualified','Disqualify immediately in every case'],answer:1,explanation:'A bounded diagnostic tests seriousness without manufacturing urgency. Refusal to investigate or confirmed low consequence could justify disqualification.'},
{prompt:'A contact requests a demo before discussing workflow. Must the seller refuse?',options:['Yes; discovery must always come first','No; clarify evaluation needs and scope a relevant short demo','No; show every feature immediately'],answer:1,explanation:'Respect the request while preventing an unfocused tour. Existing requirements, role, and buying stage determine how much discovery is necessary.'},
{prompt:'Finance and operations offer conflicting causes for the same failure. What belongs in the diagnosis?',options:['The senior stakeholder’s explanation','Both hypotheses, evidence, disagreement, and a test','An average of the two explanations'],answer:1,explanation:'Preserving disagreement prevents invented consensus. A representative sample may show different causes by workflow or segment.'},
{prompt:'Your product fits the symptom but cannot address the confirmed cause. What is strongest?',options:['Reframe the cause around the product','Disclose the limitation and recommend a better path or no sale','Offer a larger discount'],answer:1,explanation:'Disclosure supports an informed decision. New evidence that the product affects a material part of the mechanism could justify reconsideration.'}
],
'34':[
{prompt:'A model converts 3,000 saved hours into €120,000, but headcount and output will not change. What is strongest?',options:['Call all of it cash saving','Classify it as capacity and test how it can be realized','Delete the benefit without discussion'],answer:1,explanation:'Capacity is not automatic cash, but it may still matter. Avoided hiring, overtime, contractor spend, or additional throughput could change its financial classification.'},
{prompt:'A five-point change in adoption makes the base-case NPV negative. What next?',options:['Present only the base case','Treat adoption as critical uncertainty and test it before rollout','Average downside and upside'],answer:1,explanation:'Sensitivity reveals fragility. A representative pilot, stronger history, or a committed adoption plan could materially change the decision.'},
{prompt:'Operations and finance disagree on time per exception. Which number should the seller use?',options:['The higher estimate','The lower estimate','Preserve both, define the measure, and sample actual cases'],answer:2,explanation:'Choosing either estimate without investigation creates false certainty. A representative time study can resolve the disagreement and reveal variation.'},
{prompt:'The downside case is negative and no implementation owner is committed. What is strongest?',options:['Proceed because the upside is attractive','Investigate, pilot, reduce scope, or stop','Remove the downside from the presentation'],answer:1,explanation:'A full rollout is not justified. A committed owner and evidence that improves the downside threshold could support a different next step.'}
],
'35':[
{prompt:'An enterprise account has massive revenue potential but just signed a 5-year contract with your competitor. What tier should they be?',options:['Tier 1 because of their size','Monitor or Disqualify because propensity is zero','Tier 2 for marketing nurture'],answer:1,explanation:'Potential does not equal propensity. Without a trigger event, pursuing an account locked into a competitor is a massive waste of capacity.'},
{prompt:'You have 50 accounts but only capacity to deeply pursue 5. What is the strongest action?',options:['Send all 50 weekly automated emails','Tier them strictly and focus your time entirely on the top 5','Work longer hours to cover all 50'],answer:1,explanation:'Strategy requires sacrifice. Spreading scarce capacity across 50 accounts guarantees shallow work; focusing on 5 allows for deep, evidence-based account plans.'},
{prompt:'Your account plan hypothesis is "They need better software." What is the primary risk?',options:['It is too long','It is not falsifiable and lacks a specific trigger','The competitor will win on price'],answer:1,explanation:'A hypothesis must be specific and testable. "Better software" does not explain why they must change now, making it impossible to validate.'},
{prompt:'What is the strongest reason to exit an active account pursuit?',options:['They asked for a discount','The opportunity cost exceeds the learning or expected value','They haven\'t replied to one email'],answer:1,explanation:'When an account consumes capacity without yielding progress or evidence, the opportunity cost of ignoring better accounts becomes too high.'}
],
'36':[
{prompt:'A manager loves your product and promises to get it signed, but refuses to introduce you to the CFO. What role are they playing?',options:['Champion','Coach or false champion','Economic buyer'],answer:1,explanation:'A true champion has both the motivation to support you and the influence/willingness to secure access to economic decision-makers.'},
{prompt:'Five users agree they need your software. The security reviewer hasn\'t seen it yet. Do you have consensus?',options:['Yes, majority rules','No, because the security reviewer often has veto power','Yes, if the users complain loudly enough'],answer:1,explanation:'Majority support is not organizational consensus. Missing a stakeholder with veto power (like Security or Legal) usually leads to implementation failure or a blocked deal.'},
{prompt:'You need to present a business case to the VP, but your lower-level contact is defensive about giving you access. What is the strongest response?',options:['Explain that the VP requires an economic review to prevent the project from being rejected later','Go around them and email the VP directly','Ask them to just trust you'],answer:0,explanation:'Explaining how executive involvement reduces risk for the contact makes the introduction mutually beneficial and respectful.'},
{prompt:'Two stakeholders disagree on the primary cause of a workflow problem. What is the best next step?',options:['Side with the more senior stakeholder','Surface the disagreement neutrally and propose a test to find the root cause','Ignore the disagreement and focus on product features'],answer:1,explanation:'Manufacturing false consensus hides the real risk. Surfacing disagreement neutrally allows the group to align on facts before evaluating solutions.'}
]};
