/* Multi-question applied checks for every module in the depth edition. */
window.SALES_MASTERY.assessments={
'00':[
  {prompt:'A trainer states that "buyers decide emotionally and justify logically, so sell to emotion first." How should you classify and handle this claim?',options:['Accept it as an established neuroscience finding and restructure your calls around it','Treat it as a framework asserting a mechanism it cannot support; extract the testable part and check it against your own won and lost deals','Reject it entirely, since anything involving emotion is manipulation'],answer:1,explanation:'It is a framework dressed as research. The usable residue — that personal and organizational risk sit alongside financial return in real decisions — is testable. The unusable part is the implied instruction to bypass reasoning.'},
  {prompt:'Verbeke, Dietz & Verwaal found role ambiguity at β = −.25 against sales performance. Why is this described as a management finding rather than a seller finding?',options:['Because sellers cannot be expected to understand statistics','Because role ambiguity is uncertainty about expectations, measurement, and standards — all set by the organization, and fixable by writing them down','Because it only applies to junior sellers in their first year'],answer:1,explanation:'It is the only driver in the top five a manager can move in an afternoon. A team running objection-handling workshops while leaving role ambiguity untouched is optimizing a smaller variable.'},
  {prompt:'A vendor dataset shows winning calls cluster near a 46/54 talk-to-listen ratio. Your manager makes 46/54 a team KPI. What is the problem?',options:['The ratio should be 50/50 for balanced conversations','It is observational vendor data where causality may run backwards, and once it is a target a seller can hit it by saying nothing useful','Nothing — large datasets are the strongest form of evidence'],answer:1,explanation:'Two failures at once: class confusion (engaged buyers talk more, so the causal arrow is partly reversed) and Goodhart’s problem. Use it as a prompt to review a call, never as a number to be paid on.'},
  {prompt:'What distinguishes a stopping rule from simply giving up on an approach?',options:['A stopping rule is written before you have results and specifies a threshold, a sample size, and re-diagnosis','A stopping rule requires manager approval before it can be invoked','There is no meaningful difference; both end the experiment'],answer:0,explanation:'Giving up is a decision made after a bad week under emotional load with no threshold. The stopping rule exists precisely to protect you from that week, in both directions.'}
],
'01':[
  {prompt:'Which of these is an outcome rather than a feature or benefit: "automated reporting", "reports run every Friday", or "managers recover four hours each week"?',options:['Automated reporting','Reports run every Friday','Managers recover four hours each week'],answer:2,explanation:'The first is a feature (what it is), the second a benefit (what the product does). Only the third describes a change in the buyer’s situation. Note it is still capacity, not cash, until a conversion is agreed.'},
  {prompt:'Your model converts 4,000 recovered hours into £96,000 of annual value. What must you do before presenting that figure?',options:['Round it down slightly to appear conservative','State it as recovered capacity and ask which conversion applies — avoided hiring, reduced overtime, or additional throughput','Multiply by a confidence factor and present a single number'],answer:1,explanation:'Capacity becomes cash only if hours are redeployed, a hire is avoided, overtime falls, or throughput rises. A CFO who catches you converting silently will discount your entire model, and will be right to.'},
  {prompt:'A deal has an enthusiastic champion, a confirmed problem, and available budget, but you cannot describe the approval steps. Is it real?',options:['Yes — three of the four conditions is sufficient to forecast','No — the unknown decision process is the condition that most often kills late-stage deals','Yes, provided the champion confirms they will handle approvals'],answer:1,explanation:'Without the process you cannot forecast, cannot sequence proof for the people who need it, and cannot detect a missing veto holder. Ask how the last comparable purchase was actually approved.'},
  {prompt:'Why is running qualification questions during a first discovery call risky, even though qualification is legitimate?',options:['Because qualification questions are unprofessional','Because discovery serves the buyer and qualification serves you, and buyers can tell which one they are in','Because qualification should be handled entirely by marketing'],answer:1,explanation:'Both activities are legitimate. Firing budget, authority, and timeline questions at someone who came to discuss a problem converts a consultation into an audit. Earn qualification information as a by-product of genuine diagnosis.'}
],
'02':[
  {prompt:'Which Cialdini principle has the strongest replication evidence, and what is its main commercial boundary condition?',options:['Scarcity, bounded by product category','Social proof, bounded by whether the referent group is seen as genuinely comparable','Reciprocity, bounded by gift value'],answer:1,explanation:'Conformity meta-analysis across 125 Asch-type studies found a large weighted effect, and a 2023 replication reproduced rates close to the original. Comparability is the moderator: citing a global bank to a 40-person clinic can deliver no effect at all.'},
  {prompt:'A buyer has agreed with your business case for three months and still has not decided. Should you add more ROI evidence or more urgency?',options:['More ROI evidence, since the case has not yet convinced them','More urgency, since they need a reason to act now','Neither — narrow the option set, make an explicit recommendation, and shrink the size of the bet'],answer:2,explanation:'Agreement plus inaction points at indecision rather than doubt. More evidence addresses a problem they do not have; urgency raises the stakes of choosing wrongly, which omission bias converts into further delay.'},
  {prompt:'Your product genuinely has two implementation slots left this quarter. Is telling the buyer manipulation?',options:['Yes — any mention of limited availability is a pressure tactic','No, provided the constraint remains true and is stated neutrally as information rather than as a consequence','Yes, unless you also offer a discount to compensate'],answer:1,explanation:'It passes the compression test: the constraint is real and a buyer who gathered the information themselves would reach the same conclusion. If a slot frees up, tell them.'},
  {prompt:'Why does self-orientation sit in the denominator of the trust equation rather than as a fourth negative term?',options:['Because its effect is multiplicative — it discounts everything else you have built','Because it is easier to measure than the other three terms','Because it only matters in long sales cycles'],answer:0,explanation:'High self-orientation causes the buyer to reinterpret every prior good act in light of the motive. Halving it does more than doubling any other term, and the fastest way to reduce it is to recommend against your own interest once, credibly.'}
],
'03':[
  {prompt:'Traffic is strong but checkout completion is weak. What should you test first?',options:['Buy more traffic, since volume compounds through the funnel','Fix checkout friction, since improving the constrained stage multiplies every visitor you already have','Increase social posting to build brand familiarity'],answer:1,explanation:'Adding traffic multiplies revenue through the existing leak. Checkout usability research puts the average recoverable gain from redesign alone near 35% — larger than most channel expansions, with no ongoing media spend attached.'},
  {prompt:'Your mobile cart abandonment is 31 points worse than desktop. What is the most likely cause?',options:['Mobile shoppers have lower purchase intent by nature','Form and input friction on small screens — the documented gap is roughly 14 points, so 31 is about double','Your mobile pricing is displayed incorrectly'],answer:1,explanation:'A gap of double the expected size points at something specific: field count, missing digital-wallet support, keyboard type mismatches, layout shift at payment, or off-screen validation errors. Complete a purchase on a real mid-range device to find it.'},
  {prompt:'Why is ROAS a poor metric for deciding whether a channel is viable?',options:['It is calculated differently by each ad platform','It uses revenue rather than contribution margin, so it is silent on profitability and on payback period','It cannot be measured for organic channels'],answer:1,explanation:'A 4× ROAS on a 22%-margin product is a loss; a 1.8× ROAS on an 80%-margin subscription can be excellent. Judge channels on contribution after variable cost, and on payback against your cash position.'},
  {prompt:'A test shows +6% conversion after four days. Should you roll it out?',options:['Yes — a 6% lift is well above noise','No — four days is unlikely to reach the sample floor or cover a weekly cycle, and stopping when the number looks good inflates false positives','Yes, provided you monitor for a week afterwards'],answer:1,explanation:'Optional stopping raises the false-positive rate dramatically. Run to the pre-committed horizon, or use a sequential design that budgets for interim analyses in advance.'}
],
'04':[
  {prompt:'A buyer crosses their arms while you explain pricing. What should you conclude?',options:['They are resisting the price and you should address it immediately','Nothing — single non-verbal cues carry no reliable information about interest, honesty, or objection','They are comfortable and receptive'],answer:1,explanation:'Explanations range from room temperature to habit to holding a bag. Concluding "resistance" makes you worse, because a seller who believes they have read the room stops asking.'},
  {prompt:'What is the structural reason "Can I help you?" fails as an opener?',options:['It is too informal for most retail environments','It is a yes/no question with a free exit that offers no value and asks the buyer to define their need before they have oriented','It uses the word "help", which implies the customer is incapable'],answer:1,explanation:'Three defects at once. A good opener inverts all three: it gives something useful first, makes no demand, and either asks nothing or asks one specific answerable question.'},
  {prompt:'When does observed behavior become usable evidence in an in-person setting?',options:['When it is a repeated sequence rather than a single cue','When at least two colleagues observe the same thing','When the customer confirms it verbally'],answer:0,explanation:'One glance at a price tag is noise. Picking up two items, checking both tags, and returning to the first is a pattern with limited explanations — and it earns you a specific question, not a conclusion.'},
  {prompt:'Store conversion is below target and management wants a product-knowledge training day. What should you do first?',options:['Run the training, since product knowledge is a meta-analytic performance driver','Count behaviors — observe and tally 40-60 approaches by opener, brush-off, conversation length, and outcome','Increase staffing at peak hours'],answer:1,explanation:'Product knowledge is plausible, popular, and expensive. So are opener quality, stock availability, and queue length. The audit costs a few shifts and routinely finds a cheaper constraint than the one already budgeted for.'}
],
'05':[
  {prompt:'Your team’s meeting count rose 40% but qualified pipeline fell. What happened?',options:['The market softened during the period','A list problem rewarded by the wrong metric — meetings booked is gameable by loosening targeting','The messaging became less compelling'],answer:1,explanation:'Acceptable reply rates with meetings dying in first discovery points at targeting, not messaging. Change the primary metric to qualified opportunities and add a quality gate.'},
  {prompt:'Your sequence is CAN-SPAM compliant. You add 300 contacts in Germany and Canada. What must change?',options:['Nothing — CAN-SPAM is the strictest regime and covers the others','Everything about how those contacts are handled: GDPR requires a documented lawful basis, and CASL generally requires consent before the first message','Only the physical address in the footer'],answer:1,explanation:'Compliance logic does not degrade gracefully. Jurisdiction must be a field on the record evaluated before send, with a distinct sequence per regime.'},
  {prompt:'Why is open rate a poor primary metric for outbound?',options:['It is only available for HTML emails','Privacy-protection systems pre-fetch tracking pixels, so a rising rate may reflect only the mix of mail clients in your list','It cannot be segmented by campaign'],answer:1,explanation:'Machine opens are indistinguishable from human ones. It was always a weak proxy; it is now actively misleading, and optimizing subject lines against it can make a sequence worse.'},
  {prompt:'A high-fit account shows no trigger event. What is the strongest action?',options:['Contact them now, since fit is the harder criterion to satisfy','Place them in low-frequency nurture and spend the recovered effort on high-fit accounts that do have triggers','Add them to the anti-ICP'],answer:1,explanation:'Contacting a high-fit account without a trigger usually produces a polite "not right now" and spends your one good first impression at the moment of lowest receptivity. Instrument the triggers instead.'}
],
'06':[
  {prompt:'Your contact loves the product, replies within an hour, and will not introduce you to their VP. What are they?',options:['A champion who is protecting your relationship','A coach — valuable for information, unreliable for advocacy','An economic buyer testing your persistence'],answer:1,explanation:'The behavioral test has three parts: grants access upward, tells you inconvenient truths, and acts independently. Failing the access test usually means they lack standing and are embarrassed to say so — ask directly and without blame.'},
  {prompt:'Why does sending more material to an overwhelmed buying group make things worse?',options:['Because large attachments are often blocked by corporate email','Because their constraint is comprehension, not information — adding volume raises the cost of deciding','Because it signals that your product is complicated'],answer:1,explanation:'Around 55% of buyers report already facing overwhelming, conflicting information. Combined with omission bias, more input pushes the group toward doing nothing. Reconcile rather than add.'},
  {prompt:'A deal at 90% confidence dies suddenly at security review. What was the mapping error?',options:['The economic buyer was never confirmed','A veto holder was left unmapped and unengaged until too late','The champion changed roles'],answer:1,explanation:'Security, legal, compliance, works councils, and governance functions can stop a deal unilaterally and are rewarded for caution. Asked to approve in week 40 of a 42-week cycle, they default to no.'},
  {prompt:'What single test tells you whether your proposal will survive circulation without you?',options:['Give it to someone who has never met you and ask them to explain the decision back','Count the number of pages and keep it under ten','Check that every product feature is covered'],answer:0,explanation:'If they can only describe your product, it is a brochure. If they can describe the choice, the stakes, the honest arguments on each side, and what would change the answer, it works in the ~95% of the process you cannot attend.'}
],
'07':[
  {prompt:'What is the substitution test, and why does most B2B copy fail it?',options:['Replacing jargon with plain language; copy fails because writers over-use industry terms','Putting a competitor’s logo on your page — copy fails because internal review systematically removes the specificity where objections attach','Substituting statistics for adjectives; copy fails because data is hard to obtain'],answer:1,explanation:'If every sentence remains true for a competitor, the page contains atmosphere rather than a claim. It ends up optimized to survive a stakeholder meeting rather than a buyer’s scrutiny.'},
  {prompt:'Why is "up to 40%" both weak persuasion and a regulatory risk?',options:['Experienced buyers read it as an outlier, and presenting a ceiling as representative is a classic deceptive-advertising pattern','It is too vague for procurement teams to evaluate','It implies the product is inconsistent'],answer:0,explanation:'Objective performance claims must be substantiated before dissemination and typicality must not be implied where it does not exist. A range with the outlier explained is stronger on both counts.'},
  {prompt:'A customer testimonial says "this platform is the most secure on the market." Can you publish it?',options:['Yes — testimonials express the customer’s own opinion','No — it is a comparative claim, and an endorsement does not remove the substantiation requirement','Yes, provided you name the customer'],answer:1,explanation:'The advertiser is responsible for claims conveyed through endorsements, including implied ones. The customer is also not qualified to verify comparative security across a market they never evaluated.'},
  {prompt:'Why does disclosing a genuine limitation usually improve conversion quality?',options:['Because it reduces support tickets after purchase','Because credibility rises and poor-fit readers self-select out before consuming a sales conversation','Because regulators require at least one disclaimer'],answer:1,explanation:'A reader who sees you volunteer a weakness stops discounting your other claims by an unknown factor. Raw conversion usually falls slightly and downstream conversion rises substantially.'}
],
'08':[
  {prompt:'Should you always make the first offer in a negotiation?',options:['Yes — the anchoring effect is large and reliable','No — open first when you have better information about this specific value; let them open when they know the market better','No — first offers always damage the relationship'],answer:1,explanation:'The meta-analytic correlation between first offers and outcomes is around .50, and it shrinks as counterpart expertise rises. Against professional procurement with benchmark data, your anchor is a starting position, not a spell.'},
  {prompt:'A buyer says your price is 20% above a competing quote. What is your first move?',options:['Investigate what is in the other quote — scope, term, support tier, inclusions','Offer 10% immediately to show good faith','Explain why your product is worth more'],answer:0,explanation:'Gaps that size are usually scope or structure differences. Testing the comparison costs nothing, and offering the honest like-for-like quote even when it is the smaller deal is what makes any subsequent refusal credible.'},
  {prompt:'Why is conceding twice in a row without movement from the other side a serious error?',options:['It breaches most procurement codes of conduct','You are bidding against yourself, and it teaches the buyer that silence and pressure produce movement','It makes the contract harder to draft'],answer:1,explanation:'It also destroys your ability to signal a limit. Every concession must be stated as a condition before it is granted, and increments should decrease — a flat or rising pattern signals there is more behind it.'},
  {prompt:'Why keep a concession log after the deal closes?',options:['For commission verification','Because concessions become precedents at renewal, and without a log nobody can say what was traded for what','Because auditors require it'],answer:1,explanation:'A discount granted for a three-year commitment silently becomes an entitlement on a one-year renewal. The log also protects against handover loss and shows which variables the organization habitually gives away for nothing.'}
],
'09':[
  {prompt:'A buyer says "it’s too expensive." What is your first move?',options:['Reframe the value using your ROI model','Clarify which of two things they mean: more than they have, or more than they think it is worth','Offer a payment plan'],answer:1,explanation:'The first is a condition — arithmetic, not belief — where value framing changes nothing. The second is a concern that evidence can close. Responding with a value reframe to someone who lacks the money is how sellers lose access.'},
  {prompt:'Why do more evidence and more urgency make buyer indecision worse?',options:['They treat a problem the buyer does not have and inflame the one they do','They take up meeting time that could be spent on relationship building','They only work on technical evaluators, not executives'],answer:0,explanation:'An indecisive buyer already agrees. More evidence raises the volume they must reconcile; urgency raises the stakes of getting it wrong, which omission bias converts into further delay.'},
  {prompt:'You solve an objection and immediately receive a new one. What does that pattern indicate?',options:['A thorough buyer working through a checklist','Deflection — the stated objection was a socially acceptable substitute for the real reason','A competitor is feeding them questions'],answer:1,explanation:'When an objection is genuine, resolving it produces movement. The isolation question catches it early: "if we resolved that, would you move forward, or is there something else?"'},
  {prompt:'Making an explicit recommendation is the strongest move against indecision. What is its prerequisite?',options:['Approval from your sales manager','Credibility built by having recommended against your own interest before','A signed mutual action plan'],answer:1,explanation:'"I would take option B and not C" only works if the buyer believes you would say "do not buy this at all" when true. Otherwise the recommendation reads as a close and adds nothing.'}
],
'10':[
  {prompt:'Why is the assumptive close ("I’ll send the contract — shall we start on the 1st?") graded avoid?',options:['It is too direct for enterprise buyers','It makes declining a social confrontation, so the low-cost path for the buyer is evasion','It skips the pricing discussion'],answer:1,explanation:'You spend your close and learn nothing, and lose the ability to ask cleanly again. The techniques worth using all share one property: the buyer can say no without a fight.'},
  {prompt:'What is the fastest test of decision readiness?',options:['Ask whether they are ready to proceed','Ask them to explain the decision back to you as if briefing their board','Send a proposal and see how quickly they respond'],answer:1,explanation:'If they can describe the problem, the change, and the economics fluently in their own language, the first three readiness conditions are met. Hesitation or reaching for your slides is the answer, obtained without spending a close.'},
  {prompt:'A mutual action plan contains eight steps, all owned by you. What is wrong?',options:['It is too detailed for the buyer to follow','It is not mutual, so it has no predictive value — buyer-owned tasks are the actual instrument','Eight steps is too many for a healthy deal'],answer:1,explanation:'A plan with only seller tasks is a project schedule the buyer has no stake in. Buyer-owned tasks are small commitments whose slippage is the earliest reliable signal that the deal is not real.'},
  {prompt:'Why is an honest early "no" a good outcome?',options:['Because it improves your close-rate percentage','Because the realistic alternative is months of polite non-response that ends in the same place','Because it triggers a formal win/loss review'],answer:1,explanation:'An early no returns capacity to opportunities that can close, preserves the relationship for a later cycle, and usually produces the most useful information you will get about fit.'}
],
'11':[
  {prompt:'A company reports 112% net revenue retention. What is the most important follow-up question?',options:['What is the logo retention rate?','What is gross revenue retention?','What is the average contract value?'],answer:1,explanation:'NRR includes expansion, so 112% is fully compatible with 82% GRR if a few large accounts are expanding. GRR cannot exceed 100% and therefore cannot be flattered — reporting NRR alone is the most common retention deception.'},
  {prompt:'Why should "a 5% increase in retention increases profits 25-95%" not be quoted in a business case?',options:['The research has been formally retracted','The range came from specific industry models and was never established as a cross-industry constant','Retention has no measurable effect on profit'],answer:1,explanation:'The mechanism is sound and arithmetically obvious. Model it for your own business — twenty minutes produces a number tied to your actual margins and churn curve that survives a CFO asking where it came from.'},
  {prompt:'Why does time-to-first-value predict churn better than go-live date?',options:['Because go-live dates are often recorded inaccurately','Because it determines whether the buying decision has been proven and the champion vindicated','Because value is measured by the customer rather than the vendor'],answer:1,explanation:'A customer with evidence can defend the purchase internally. One still waiting at month five has an unproven decision, an exposed champion, and a growing internal argument they cannot win.'},
  {prompt:'Your champion has just left the customer. What is the appropriate response window and posture?',options:['Wait for the successor to make contact, to avoid appearing intrusive','72 hours, and treat it as a new sale — the institutional memory of why you were bought has left','30 days, aligned to the next scheduled business review'],answer:1,explanation:'Send the original business case and realized value to the successor, offer a briefing framed as "you inherited this", have an executive contact their counterpart, and flag the account at-risk regardless of contract length.'}
],
'12':[
  {prompt:'What distinguishes influence from manipulation?',options:['The evidence behind the claim, not the technique used','Whether the buyer is a consumer or a business','Whether the seller intends to help'],answer:0,explanation:'Almost every technique can be either. Influence compresses evidence the buyer would endorse if they had gathered it themselves; manipulation uses the identical technique with the evidence removed.'},
  {prompt:'A buyer makes an incorrect assumption in your favour and does not ask about it. Must you correct them?',options:['No — you made no false statement','Yes, if a reasonable buyer would want to know; omission is the most common form of sales dishonesty','Only if it materially affects the price'],answer:1,explanation:'The assumption will be discovered, usually in month three when you have no leverage and no goodwill. Correcting a buyer’s error in your own favour is also one of the fastest credibility-building acts available.'},
  {prompt:'Your contract has a 90-day cancellation notice that improves reported retention. Is this a dark pattern?',options:['No — notice periods are standard commercial practice','Yes — it is a roach-motel term that improves the metric by removing choice rather than giving a reason to stay','Only if the customer objects to it'],answer:1,explanation:'The diagnostic is whether cancellation is as easy as signing up. Organizations that shorten these periods frequently find retention unchanged, which reveals the term was protecting nothing but the number.'},
  {prompt:'Why is treating sales misconduct primarily as a character problem a mistake?',options:['Because it guarantees recurrence — most misconduct is rational responses to incentive design','Because character cannot be assessed reliably in interviews','Because compliance training is legally sufficient'],answer:0,explanation:'Commission paid entirely at signature makes a churning deal profitable for the seller; measuring meetings booked makes loose targeting rational. Ethics training changes none of those payoffs.'}
],
'13':[
  {prompt:'What single question should you ask about every tool in your stack?',options:['How many users have logged in this month?','Name a decision that was made differently last quarter because of this tool','What is the annual cost per seat?'],answer:1,explanation:'Not a report it generated — a decision that changed. In most audits the biggest finding is a tool already owned but never deployed for the purpose the evidence supports.'},
  {prompt:'Why is intent data a poor purchase for a team without a defined ICP?',options:['Intent signals are unreliable in most industries','Prioritisation requires something to prioritise against; without an ICP the data produces activity rather than focus','It duplicates data already in the CRM'],answer:1,explanation:'You cannot distinguish a high-intent account worth pursuing from one that will never buy, so poor-fit accounts start to look urgent. Define the ICP and anti-ICP first.'},
  {prompt:'An AE says they want to get better at closing. Why is that usually the wrong constraint?',options:['Closing skill is innate and cannot be trained','Deals that die at the end are usually lost earlier — at diagnosis, coverage, or unbounded risk','Closing is the responsibility of the sales manager'],answer:1,explanation:'Locate the constraint in data: compare stage-to-stage conversion against a median, then examine the last ten losses at the weak stage for a common factor. It usually names something quite different.'},
  {prompt:'What distinguishes deliberate practice from experience?',options:['Deliberate practice requires a formal certification programme','A specific isolated sub-skill, immediate external feedback, and repetition with correction','Deliberate practice happens outside working hours'],answer:1,explanation:'Ten years of calls without recording, scoring, or rehearsing produces experience and little skill. This is why conversation intelligence is high-return for coaching and worthless as surveillance.'}
],
'14':[
  {prompt:'What is the right question to ask before delegating a task to an AI system?',options:['Can the model produce a plausible output for this task?','If the output is wrong, how quickly will I know and what will it cost?','Is the model trained on data from our industry?'],answer:1,explanation:'That resolves into verifiability and reversibility. Safest where you hold the ground truth; most dangerous where the system supplies external facts that reach a buyer, because a fabricated claim reads exactly like a true one.'},
  {prompt:'Your team has human review for AI-drafted emails. Why might it not be a control?',options:['Reviewers may not be senior enough','Because review quality degrades non-linearly with throughput — 340 emails released in 25 minutes is a rubber stamp','Because reviewers cannot see the original prompt'],answer:1,explanation:'The test is arithmetic: calculate reviewed items per reviewer per hour and ask whether a human could genuinely read that many. Rate limits and removing bulk-approve are real safety controls.'},
  {prompt:'Is it acceptable to run an AI agent that emails prospects under a plausible human name?',options:['Yes, provided the emails are accurate','No — presenting an automated system as a named human colleague is a misrepresentation','Yes, if the name is disclosed on your website'],answer:1,explanation:'Deceptive-practice rules apply to commercial communication regardless of technology, and it fails the disclosure test immediately. Buyers object to being deceived, not to being contacted by an assistant.'},
  {prompt:'An account-scoring model is trained on three years of closed-won data. What should you watch for?',options:['Feedback loops that reproduce the team’s past coverage rather than the market’s potential','Model drift caused by seasonal variation','Overfitting to the largest accounts'],answer:0,explanation:'Regions the team never covered appear as poor prospects, so the model down-ranks them and they continue to receive no coverage. Audit what the model down-ranked and reserve capacity for model-dissenting accounts.'}
],
'15':[
  {prompt:'Why is "99% accurate" a weak claim to a technical evaluator?',options:['The figure is too high to be plausible','It has no denominator, task definition, or measurement method, so it cannot be tested','Accuracy is the wrong metric for most AI systems'],answer:1,explanation:'An untestable number is assumed to be the most favourable one available. The credible form specifies the metric, the population, how ground truth was established, and where performance degrades.'},
  {prompt:'A buyer asks whether your system hallucinates. What is the honest answer?',options:['No — our retrieval architecture prevents it','It can, and here is the shape of our observed errors, how we test for the dangerous class, and what happens when the system is uncertain','That depends on how you define hallucination'],answer:1,explanation:'Any probabilistic generative system can produce a confident wrong output. Denying the category ends your credibility with anyone who understands the technology; a stated error rate is something buyers can work with.'},
  {prompt:'Why is abstention often worth more to a buyer than an extra point of accuracy?',options:['Because it reduces compute cost','Because it determines the operational cost of errors — uncertainty concentrated in a visible queue can be staffed and measured','Because regulators require confidence thresholds'],answer:1,explanation:'A system that always answers distributes its errors invisibly through the workflow, where they compound and are discovered downstream. The practical question is what happens on the 6% you are unsure about.'},
  {prompt:'Why should an AI pilot include an explicit failure condition?',options:['To satisfy procurement documentation requirements','Because it is a costly signal and it converts an open-ended experiment into a bounded, reversible decision','To limit the vendor’s liability exposure'],answer:1,explanation:'No vendor with a weak product volunteers a threshold below which they withdraw at no charge. It also addresses omission bias in a buyer stalled by fear of choosing wrongly rather than by doubt.'}
],
'16':[
  {prompt:'Why is a free pilot worse than a heavily discounted one?',options:['Free pilots take longer to convert','Money is the only demand signal that survives politeness — free tells you only that people accept free things','Free pilots attract lower-quality customers'],answer:1,explanation:'A discounted paid partnership creates a real commitment: someone had to approve it, which means someone had to articulate why. Charge something, and require obligations on their side as part of the discount.'},
  {prompt:'A prospect will sign if you build a specific feature. What is the first question to ask?',options:['How long will it take engineering to build?','Which of my next ten target customers would also use this — and can I name three?','What is the prospect willing to pay for it?'],answer:1,explanation:'Three named customers means it is generalizable and belongs on the roadmap. One means it is account-specific and must be priced at services rates or declined. Skipping this is how a product company becomes a consultancy.'},
  {prompt:'What is the actual trigger for hiring a first salesperson?',options:['Reaching a revenue milestone such as £1m ARR','A written repeatable pattern plus founder capacity becoming the binding constraint','Securing a funding round'],answer:1,explanation:'Hiring before the pattern exists asks the hire to discover the motion while carrying a quota, without any of the founder’s transferable advantages — and the failure is then misattributed to the hire.'},
  {prompt:'You close ten customers through ten different paths with bespoke work for each. Do you have traction?',options:['Yes — ten paying customers is traction by any definition','No — you have ten paid interviews, because nothing about the motion is repeatable','Yes, provided revenue is growing month on month'],answer:1,explanation:'The diagnostic is whether you can write down what the customers had in common. If you cannot, hiring a seller against that revenue will fail.'}
],
'17':[
  {prompt:'Why is "logged in 10 times this week" a poor product-qualified-lead signal?',options:['Login data is often inaccurate','It measures activity rather than benefit, and is generated equally by customers, students, and competitors','Ten logins is too low a threshold'],answer:1,explanation:'Validated against conversions it typically shows high recall and terrible precision. What predicts is a value signal combined with a constraint signal and account fit.'},
  {prompt:'A user has reached first value and shows no constraint signal. What should sales do?',options:['Nothing, or send genuinely useful automated guidance with no ask','Call them, since engaged users are the warmest leads','Offer a discount to accelerate expansion'],answer:0,explanation:'The user is succeeding without you. Interrupting a working experience to sell converts a functioning revenue channel into an annoyance, and the damage shows up as quiet non-expansion rather than in any sales report.'},
  {prompt:'What is the highest-value signal most product-led sales teams never look for?',options:['Feature adoption depth','Departmental spread — multiple separate teams inside one organization, each on their own small plan','Time spent in the product per session'],answer:1,explanation:'Each account looks trivial, so nobody routes it, while together they represent a consolidation opportunity often worth more than any new logo. Surfacing it needs only a weekly job aggregating by email domain.'},
  {prompt:'What is the test for whether a product-triggered message is worth sending?',options:['Whether it mentions a feature the user has not tried','Whether the user could have learned it from the product — if yes, do not send it','Whether it includes a calendar link'],answer:1,explanation:'What passes: configuration insight, peer benchmarks, organizational facts they cannot see, and honest limitations. Advice that reduces what they will spend is the strongest signal of all.'}
],
'18':[
  {prompt:'Why is role ambiguity described as the largest fixable variable in sales management?',options:['It has the largest absolute effect size of any driver in the literature','It carries a meta-analytic β of −.25, is entirely within a manager’s control, and can be reduced in an afternoon','It is the only driver that applies to every sales role'],answer:1,explanation:'Write down four things: outcome expectations, quality standards with exemplars, decision rights, and priority. It goes unaddressed because it is invisible to the manager, who already knows what they mean.'},
  {prompt:'Why should coaching and pipeline inspection never happen in the same meeting?',options:['Because they require opposite psychological states — defending versus exposing weakness','Because managers lack time to do both properly','Because inspection is a group activity and coaching is individual'],answer:0,explanation:'A seller who has just justified a forecast will not then admit they do not know how to ask for CFO access. Separate them by day and format, and never cancel coaching under quarter-end pressure.'},
  {prompt:'A seller says a deal is going "really well" and the champion is "fully bought in." What should the manager ask?',options:['Whether the seller has sent a proposal yet','For buyer evidence: who the economic buyer is, when they were last spoken to directly, and what has come back in writing','Whether the champion has confirmed a close date'],answer:1,explanation:'Enthusiasm and rapport are seller-side signals uncorrelated with outcome. If evidence is absent, apply the category definition impersonally so the downgrade is a rule rather than a judgment.'},
  {prompt:'Where does coaching capacity usually go, and where should it go?',options:['To the top performers; it should go to the bottom','To the bottom performers; a deliberate allocation across bottom, middle, and top usually returns more','It is evenly distributed already in most teams'],answer:1,explanation:'Moving a seller from 85% to 105% adds more absolute revenue than moving one from 40% to 55%, and they are more likely to stay. Audit your calendar for where coaching time actually went.'}
],
'19':[
  {prompt:'Is narrative more persuasive than statistical evidence?',options:['Yes — stories consistently outperform statistics across audiences','The literature is mixed; what is better established is that narrative is substantially more memorable','No — statistics outperform narrative whenever the audience is technical'],answer:1,explanation:'Use story as a transport mechanism so your argument survives being retold in a meeting you are not in, and attach numbers so it survives being checked.'},
  {prompt:'Why is making your company the hero of a customer story a structural error?',options:['It breaches most customer confidentiality agreements','It removes the person the listener is supposed to identify with, and it is usually inaccurate','It makes the story too long'],answer:1,explanation:'A buyer facing a difficult decision needs to see someone like them making that decision and being right. The fix is grammatical: make the customer the subject of nearly every sentence.'},
  {prompt:'What does adding typicality to a customer result achieve?',options:['It stops the listener assuming you quoted your best case, and it satisfies endorsement rules on representativeness','It shortens the story','It removes the need for a named reference'],answer:0,explanation:'Knowing the median matters more to a buyer’s own forecast than knowing the maximum. Counter-intuitively, revising your headline number downward usually increases how much of it is believed.'},
  {prompt:'In a change narrative, why quantify the cost of the status quo rather than the benefit of change?',options:['Because cost figures are easier to verify','Because status quo bias means inaction is evaluated as free until something makes its cost visible','Because buyers distrust projected benefits'],answer:1,explanation:'The essential companion move is to make the first step small and reversible. Making inaction expensive without making action small only raises the stakes on a decision the buyer already feared getting wrong.'}
],
'20':[
  {prompt:'What is the evidential status of mimetic theory, and how should that change your use of it?',options:['It is an empirical finding with a measured effect size; apply it directly','It is an interpretive philosophical framework; use it to generate questions, never conclusions about a person','It has been refuted and should be discarded entirely'],answer:1,explanation:'What is well supported is the underlying phenomenon — social influence, with perceived similarity to the referent as the critical moderator.'},
  {prompt:'Why does a vendor’s largest logo often fail as a reference?',options:['Large customers rarely agree to reference calls','Prestige is not comparability, and social proof depends on the referent being seen as similar','Their contracts usually prohibit disclosure'],answer:1,explanation:'A 900-person society hearing about a global bank concludes the opposite of what the vendor intends. Structural and constraint similarity and status proximity all predict better than scale or fame.'},
  {prompt:'What single question replaces most guessing about a buyer’s reference group?',options:['"Who are your main competitors?"','"When you are weighing something like this, whose approach do you actually pay attention to?"','"Which analyst reports do you read?"'],answer:1,explanation:'The answers are regularly not what the vendor assumed — a regulated firm may name anyone under the same rulebook regardless of industry. It costs one sentence and routinely reorders a reference strategy.'},
  {prompt:'When does using a competitor as a reference become manipulation?',options:['Whenever the competitor is named without their permission','When it is asserted without evidence or deployed to manufacture pressure — "your competitors are already ahead"','Whenever the buyer has not asked about competitors'],answer:1,explanation:'The legitimate version is factual, neutral, and consented: ask first, respect the answer, and present what happened including where it did not work.'}
],
'21':[
  {prompt:'Which of these behavioral findings should a seller stop relying on?',options:['Status quo bias and omission bias','Social and behavioral priming, ego depletion, and any specific loss-aversion ratio such as 2:1','Framing effects and default effects'],answer:1,explanation:'Priming saw multiple high-profile replication failures, ego depletion effects came out near zero in multi-lab replications, and a 2024 meta-analysis places the loss-aversion coefficient below the frequently-quoted ratio.'},
  {prompt:'Is choice overload real?',options:['Yes — fewer options always sell more','Conditionally — meta-analysis finds a near-zero average effect, with real effects where options are complex and preferences unformed','No — the original study was retracted'],answer:1,explanation:'That condition describes most enterprise evaluations. So the guidance survives while the universal law does not: reduce options because this buyer cannot evaluate them, then make an explicit recommendation.'},
  {prompt:'What distinguishes friction reduction from choice manipulation?',options:['Direction — removing obstacles from a decision the buyer wants to make, versus engineering one they would not','Whether the technique is disclosed in the terms and conditions','Whether the buyer is a consumer or a business'],answer:0,explanation:'The same mechanisms serve both. The test is whether you would be comfortable if the buyer saw exactly what you were doing: a default you would explain proudly is legitimate; one you would rather they did not notice is a dark pattern.'},
  {prompt:'In a decision-friction audit, why is the biggest win often not psychological?',options:['Because cognitive biases are largely unfixable','Because procedural friction — security reviews starting late, sequential legal review — usually costs more elapsed time and is cheaper to fix','Because buyers are less susceptible to biases than research suggests'],answer:1,explanation:'A team looking only for cognitive biases will walk straight past them. Map the buyer’s actual path with real dates before any behavioral analysis.'}
],
'22':[
  {prompt:'What does the evidence say about preferred representational systems?',options:['They exist but are difficult to detect reliably in conversation','They do not exist in the form NLP claims — predicate-matching reviews found correlations typically below .30 and no stable system','They have been confirmed by neuroimaging studies'],answer:1,explanation:'Broader reviews are equally unfavourable: roughly 18% of 315 NLP publications were supportive, and 89% of 33 health-outcome studies lacked control groups.'},
  {prompt:'If a technique is harmless, why does believing a false mechanism still matter?',options:['Because it replaces inquiry with classification — a seller who has categorized a buyer stops asking','Because it violates professional certification standards','Because clients may request evidence for the method'],answer:0,explanation:'False models also produce confident error, since training raises certainty faster than accuracy, and they consume preparation time better spent on the buyer’s business.'},
  {prompt:'Why is deliberate mirroring a bad bet even setting the evidence aside?',options:['It is physically difficult to sustain in long meetings','The payoff is asymmetric — unnoticed it gains nothing measurable, noticed it is expensive to recover from','It only works in face-to-face settings'],answer:1,explanation:'Pace, silence, and reusing the buyer’s own terminology work through mechanisms that survive detection entirely — a buyer who notices those is pleased.'},
  {prompt:'Which NLP-adjacent practices are worth keeping?',options:['Eye-accessing cues and state anchoring','Reusing the buyer’s terms, adjusting pace and leaving silence, offering a choice of evidence format, and future-state questioning','Predicate matching and identity-level language'],answer:1,explanation:'Each has an ordinary explanation requiring no neuroscience. Future-state questioning should always be paired with its disconfirming half: "and what could stop that?"'}
],
'23':[
  {prompt:'Why can a fully completed MEDDPICC record make a forecast worse?',options:['Because it takes time away from selling','Because completion is not evidence — fields filled with beliefs display a qualified deal where none exists','Because the framework has too many letters to maintain'],answer:1,explanation:'The fix is the three-state rule: mark every element confirmed with a cited source and date, assumed, or unknown — and never let "assumed" quietly become "confirmed."'},
  {prompt:'What three behaviors distinguish a champion from a coach?',options:['Responsiveness, enthusiasm, and product knowledge','Granting access upward, telling you inconvenient truths unprompted, and taking action when you are absent','Attending demos, sharing documents, and introducing you to peers'],answer:1,explanation:'Two of three is a working champion. When someone fails the access test, ask directly and without blame — the reason is usually that they lack standing and are embarrassed to say so.'},
  {prompt:'Why ask "what happened last time you bought something this size?" rather than "what is your decision process?"',options:['Past-event questions produce the real sequence; process questions produce the official one','It is less intrusive and easier to answer','It gives you the contract value of the previous purchase'],answer:0,explanation:'People describe how purchasing is supposed to work when asked abstractly, and what actually happened — legal took three weeks, procurement demanded two more quotes, the board does not meet in August — when asked about a remembered event.'},
  {prompt:'What is a backward pass and why does it matter?',options:['Reviewing the deal history from first contact to today','Working back from the buyer’s required decision date through every dependency to find when each step must start','Re-qualifying a deal that has slipped a quarter'],answer:1,explanation:'In a large share of enterprise deals it reveals the stated timeline was never achievable, and often that a step should already have started. Discovering that jointly in March is a different conversation from discovering it alone in August.'}
],
'24':[
  {prompt:'Procurement claims to have comparable quotes 30% below yours. What is your first move?',options:['Ask what is in them — which products, what scope, what term, what support tier','Match the price to stay in the evaluation','Escalate to the business sponsor who selected you'],answer:0,explanation:'Gaps that size are usually scope or structure differences, and very often the benchmark is never produced. Testing the comparison costs nothing.'},
  {prompt:'Why is going around procurement to the business sponsor a serious error?',options:['It usually breaches the supplier code of conduct','Procurement controls the paper process you depend on, and they will hear about it','It delays the legal review by several weeks'],answer:1,explanation:'It converts a professional counterpart into an adversary precisely when you need them to move quickly, and signals that you regard their mandate as illegitimate.'},
  {prompt:'What single question most improves a procurement engagement?',options:['"What is your target discount?"','"What does a good outcome on this look like for you, beyond price?"','"Who else are you evaluating?"'],answer:1,explanation:'The answer routinely reveals objectives that cost you very little — a capped uplift, a rate card, consolidation of overlapping contracts — while giving procurement a better internal result than the flat discount they were mandated to seek.'},
  {prompt:'Why should you never trade a liability cap for price?',options:['Because legal teams rarely approve it in time','Because liability is an asymmetric, potentially existential exposure while price is bounded and recoverable','Because it has no value to procurement'],answer:1,explanation:'Unlimited liability on a £400k contract can produce a loss orders of magnitude larger than the deal. Trade it only against matching commitment, and only with legal approval.'}
],
'25':[
  {prompt:'Why does showing more features often reduce win rate?',options:['Longer demos exceed the buyer’s attention span','Each additional feature consumes relevant attention, creates a comparison point, and raises the buyer’s estimate of implementation complexity','Buyers assume broader products cost more'],answer:1,explanation:'A tour of thirty screens hands the buyer thirty opportunities to find you wanting, mostly about capabilities they will never use.'},
  {prompt:'What is the difference between a demo and proof?',options:['A demo is live and proof is recorded','A demo shows a capability exists; proof shows it produces a specific result in the buyer’s environment against a criterion they defined','A demo is for users and proof is for executives'],answer:1,explanation:'Every proof activity needs five things agreed in writing beforehand: the uncertainty, the criterion, the baseline, the scope and end date, and the decision that follows each outcome.'},
  {prompt:'Why open a demo by asking what would make it worth the attendees’ time?',options:['It fills time while latecomers join','Because the answers are frequently different from what the demo was built for, especially from attendees you have not met','Because it is a standard courtesy in enterprise settings'],answer:1,explanation:'A ward manager whose concern is whether her team can use it will not be served by a session built around head-office reporting — and if you do not ask, you find out when she objects late or silently blocks it.'},
  {prompt:'Why is a stated failure condition the most persuasive element of a proof plan?',options:['It reduces the vendor’s commercial risk','It is a costly signal no weak-product vendor would offer, and it converts an open-ended commitment into a bounded, reversible one','It satisfies procurement documentation requirements'],answer:1,explanation:'That combination is precisely what addresses omission bias in a buyer stalled by fear of choosing wrongly rather than by doubt about the product.'}
],
'26':[
  {prompt:'Why is outcome-based self-assessment unreliable in sales?',options:['Because outcomes are recorded inconsistently in most CRMs','Because outcome variance is high and the feedback lag is long, so an outcome is a noisy signal arriving months late','Because quotas differ between sellers'],answer:1,explanation:'A well-run deal can be lost to a budget freeze; a badly-run one can close because the incumbent had an outage. Score the process, which you control and can observe within days.'},
  {prompt:'Which cell of the process/outcome grid is most dangerous?',options:['Good process with a bad outcome','Bad process with a good outcome','Bad process with a bad outcome'],answer:1,explanation:'Nobody reviews a win, so the habit is reinforced rather than examined — and it will fail as soon as deals get larger or conditions harder. Review wins with the same scepticism as losses.'},
  {prompt:'Why review losses in batches of ten rather than individually?',options:['Because one loss carries little signal and the most recent is the most emotionally loaded','Because managers only have time for quarterly reviews','Because CRM reporting works in batches'],answer:0,explanation:'A batch reveals which criterion fails repeatedly. That repeated element is the real, controllable finding — usually no economic-buyer contact, no confirmed problem statement, or no disqualification discipline.'},
  {prompt:'How do you distinguish a variance slump from a process slump?',options:['By comparing your results to the team median','By checking whether your weekly process scores and leading-activity volume have held','By counting the number of deals lost to competitors'],answer:1,explanation:'If both held, it is variance and the correct action is to change nothing. If a process score declined, fix that one thing. The two require opposite responses, and adding effort to a variance slump usually manufactures the next one.'}
],
'27':[
  {prompt:'What is the evidential status of Transactional Analysis, and what does it permit?',options:['Strong clinical evidence; it may be used to assess buyer psychology','Limited — reviews find a small, methodologically weak literature; it permits describing interaction patterns, not diagnosing people','It has been formally refuted and should not be used at all'],answer:1,explanation:'"This exchange has become instructing and complying" is legitimate. "She operates from Child ego state" is not — there is no validated measurement instrument.'},
  {prompt:'Why is rescuing a problem when it feels helpful to both parties?',options:['It puts you in a position you cannot deliver from, with no named owner on the buyer’s side','It takes time away from prospecting','It creates unbillable work'],answer:0,explanation:'A business case authored by a vendor reads differently to a board than one from an internal sponsor, and nobody on their side is invested. The tell: you are doing work their organization should own.'},
  {prompt:'What is the tell for deferring, and why is it the most expensive pattern?',options:['Leaving a meeting without asking the question you knew you should ask; the cost lands months later and is attributed elsewhere','Agreeing to every request for a discount; the cost appears immediately in margin','Sending too many follow-up emails; the cost is reputational'],answer:0,explanation:'Four months of accepting "he is taking it up" is not patience — it is a question unasked, and the answer is usually available in one sentence.'},
  {prompt:'In an escalation meeting, why does "leave it with me" make things worse?',options:['It commits you to a timeline you cannot control','It completes a drama triangle rather than breaking it, removes the customer’s agency, and establishes nothing checkable','It implies the customer was at fault'],answer:1,explanation:'You take on an obligation you probably cannot deliver, and no cause, owner, date, or criterion is established — so the next slip becomes a personal betrayal rather than a project issue.'}
],
'28':[
  {prompt:'What is the status of Polyvagal Theory’s core physiological claims?',options:['Established and widely replicated','Disputed in the primary literature on comparative-anatomy and cardiac-physiology grounds','Confirmed for adults but not for children'],answer:1,explanation:'The practical advice carried alongside it — reduce avoidable pressure, allow silence, notice disengagement — is sound for ordinary reasons and survives the theory’s problems entirely.'},
  {prompt:'If the advice is good, why does the disputed mechanism matter?',options:['Because a false mechanism licenses false inferences, imports clinical language, and obscures the real causes','Because trainers who teach it may lose certification','Because it makes the advice harder to remember'],answer:0,explanation:'If tension is explained as physiological you look for a physiological remedy. If it is the ordinary result of an ambiguous high-consequence decision plus vendor deadline pressure, you look at what you are doing.'},
  {prompt:'What proportion of tension in a sales conversation is typically added by the seller?',options:['Almost none — tension is inherent to commercial decisions','Most of it — ambiguity, artificial deadlines, arriving outnumbered, no graceful exit, and talking density are all seller-introduced','About half, split evenly between both parties'],answer:1,explanation:'Only the consequence of the decision itself and some status asymmetry are genuinely inherent. A seller who eliminates only their own contributions will improve most difficult conversations.'},
  {prompt:'A buyer agrees rapidly with everything you say. What does that suggest?',options:['Strong conviction and readiness to proceed','Often the opposite — agreement is the cheapest way to end a conversation','That your discovery was unusually thorough'],answer:1,explanation:'Say so without accusation: "you have agreed with everything, which makes me think I have not asked a hard enough question — what is the part you are least convinced by?"'}
],
'29':[
  {prompt:'Why is "get inside your competitor’s decision cycle" bad advice for complex sales?',options:['Competitors rarely have a definable decision cycle','It misreads Boyd, whose emphasis was orientation, and it treats the buyer’s deliberation as an obstacle','It only applies to transactional selling'],answer:1,explanation:'A fast loop running on a wrong model is worse than a slow one, and compressing a buyer’s evaluation adds pressure to the exact variable that responds badly to it.'},
  {prompt:'What is orientation and why does it decide the outcome?',options:['The stage of the buying process the customer has reached','The model through which observations acquire meaning — every subsequent step inherits it','The alignment between sales and marketing messaging'],answer:1,explanation:'Two sellers observing "the champion has gone quiet" will act completely differently. None is perceiving; all are interpreting. A wrong orientation held confidently produces fast, decisive, wrong action.'},
  {prompt:'What is the cheapest way to shorten the interval between observation and an updated model?',options:['A written summary after every substantive conversation, asking for correction','Weekly pipeline reviews with your manager','More frequent CRM updates'],answer:0,explanation:'Buyers correct written errors they would never raise verbally — interrupting someone mid-sentence is socially costly, replying to a bullet is not. It takes four minutes.'},
  {prompt:'A buyer mentions they have added other vendors. What is the correct first move?',options:['Offer a discount to protect your position','Ask three questions: who are they, whose decision was it, and has the requirement changed','Accelerate to a decision before the others can present'],answer:1,explanation:'The answers frequently separate a procedural three-quote threshold from a genuine competitive shift, which need opposite responses. Reactive discounting signals that the price was never real.'}
],
'30':[
  {prompt:'What is wrong with explaining a buyer’s resistance as "coalition defence"?',options:['It is offensive to the buyer if overheard','It changes nothing you would do and cannot be disconfirmed','It is only applicable in large organizations'],answer:1,explanation:'The situational version — "his budget or headcount case may depend on owning this function" — is checkable in one question and frequently wrong in an informative way. An explanation that alters no action and admits no test is decoration.'},
  {prompt:'What is the difference between surfacing and exploiting personal risk?',options:['Whether the risk already exists — surfacing names a real asymmetry and reduces it; exploiting manufactures a career threat','Whether the buyer raises it first','Whether it is discussed in writing or verbally'],answer:0,explanation:'"Here is documentation that would let you defend this decision" is legitimate. "Imagine explaining to your board why you did not do this" fails both the compression and disclosure tests.'},
  {prompt:'Why is "describe the situation, not the person" the load-bearing guardrail on this lens?',options:['Because situations are checkable and changeable while dispositions are neither','Because personal descriptions may breach data-protection rules','Because buyers dislike being characterised'],answer:0,explanation:'"He is territorial" ends inquiry and suggests no action. It is also where the lens slides into stereotyping — from what kind of person someone is to what kind of people behave that way is a very short step.'},
  {prompt:'Your sponsor has been enthusiastic for months and will not escalate. What is the likely structural cause?',options:['They do not believe the business case','Asymmetric personal exposure — it is their recommendation alone, so success is shared and failure is attributable','They are waiting for budget approval'],answer:1,explanation:'More evidence will not solve it because the case was never the obstacle. Distribute the decision through shared criteria set by other stakeholders, and document what was considered so it is defensible.'}
],
'31':[
  {prompt:'During market research for a new SaaS product, 10 target buyers say they "love the concept and would definitely buy it," but none have attempted to solve the problem using existing tools or allocated budget. What is the correct assessment of market demand?',options:['Stated enthusiasm equals confirmed market demand, so building should begin immediately','Hypothetical intention is weak evidence; demand is unproven until buyers demonstrate past behavioral pain or commit resources','The sample size of 10 is too small, so you should survey 500 more people with the same question'],answer:1,explanation:'Hypothetical statements and compliments are weak evidence of fit. True demand requires observable past behavior, active search, or committed capital/time.'},
  {prompt:'An interviewer asks a prospect: "Would an automated document reminder save your team 5 hours a week?" What is the primary flaw in this interview technique?',options:['The question is too short to yield detailed technical requirements','It is a leading, solution-first question that invites politeness rather than uncovering actual past workflow sequence','It should have offered a discount before asking about saved time'],answer:1,explanation:'Leading questions frame the answer and invite polite agreement. Effective customer research anchors in past concrete events ("Walk me through the last time...") to reveal real behavior.'},
  {prompt:'After losing an enterprise deal, the sales rep logs the reason as "lost on price." During an independent post-decision interview, the buyer reveals they chose a competitor because of implementation risk. What does this demonstrate?',options:['Buyers always lie to sales reps about financial constraints','Rep-reported loss reasons are often self-serving deflections; credible win/loss requires independent, open-ended post-decision reviews','The seller should have offered a 30% discount earlier'],answer:1,explanation:'Win/loss data collected by direct sellers frequently defaults to price. Independent reviews reveal structural root causes like consensus breakdown, risk, or implementation fears.'},
  {prompt:'In a research cohort of 10 target accounts, 8 describe a severe workflow bottleneck, while 2 report no issue because they built an internal script. How should the researcher handle the 2 non-conforming accounts?',options:['Discard the 2 accounts as outliers to present a clean 100% problem consensus','Investigate the difference to determine if technical capability or company size defines a specific segment boundary','Force the 2 accounts to adopt the proposed solution anyway'],answer:1,explanation:'Negative cases and non-conforming accounts reveal critical segment boundaries or alternative workarounds, preventing false consensus.'}
],
'32':[
{prompt:'A prospect shows strong web intent but requires a deployment model you cannot support. What is strongest?',options:['Fast-track the opportunity because intent is high','Clarify whether the requirement is mandatory and disqualify if it is','Offer a discount to offset the limitation'],answer:1,explanation:'Intent does not repair poor fit. Clarification and, when necessary, disqualification protect both parties. A supported alternative or a changed requirement could alter the decision.'},
{prompt:'Two groups report the same problem, but one self-serves and the other requires a six-month security process. What should you do?',options:['Keep one segment because the problem is identical','Model them separately because buying process and cost to serve differ','Choose the faster group without further evidence'],answer:1,explanation:'Segments should predict different decisions. Combining them hides motion, proof, and economic differences; speed alone may ignore greater durable value. Retention, margin, and reachable demand could change priority.'},
{prompt:'Buyers praise a differentiator but rarely use it after purchase. What is strongest?',options:['Keep leading with it because interviews were positive','Downgrade the claim until behavior or outcome evidence supports it','Remove the feature immediately'],answer:1,explanation:'Praise is weak evidence of realized value. Downgrading the claim preserves uncertainty without overreacting. If the feature works passively, a better outcome measure could restore the claim.'},
{prompt:'One proposed ICP has high win rate but poor retention. Is it proven?',options:['Yes, acquisition proves fit','No; investigate selection, implementation, margin, and realized value','Yes, if sales cycles are short'],answer:1,explanation:'Win rate measures acquisition, not durable fit. Cohort retention, time-to-value, margin, and causal evidence may support or reject the segment.'}
],
'33':[
{prompt:'A buyer reports a serious problem but has not measured it or assigned an owner. What is strongest?',options:['Push for a decision while concern is high','Propose a small diagnostic action and keep it unqualified','Disqualify immediately in every case'],answer:1,explanation:'A bounded diagnostic tests seriousness without manufacturing urgency. Refusal to investigate or confirmed low consequence could justify disqualification.'},
{prompt:'A contact requests a demo before discussing workflow. Must the seller refuse?',options:['Yes; discovery must always come first','No; clarify evaluation needs and scope a relevant short demo','No; show every feature immediately'],answer:1,explanation:'Respect the request while preventing an unfocused tour. Existing requirements, role, and buying stage determine how much discovery is necessary.'},
{prompt:'Finance and operations offer conflicting causes for the same failure. What belongs in the diagnosis?',options:['The senior stakeholder’s explanation','Both hypotheses, evidence, disagreement, and a test','An average of the two explanations'],answer:1,explanation:'Preserving disagreement prevents invented consensus. A representative sample may show different causes by workflow or segment.'},
{prompt:'Your product fits the symptom but cannot address the confirmed cause. What is strongest?',options:['Reframe the cause around the product','Disclose the limitation and recommend a better path or no sale','Offer a larger discount'],answer:1,explanation:'Disclosure supports an informed decision. New evidence that the product affects a material part of the mechanism could justify reconsideration.'}
],
'34':[
{prompt:'A model converts 3,000 saved hours into €120,000, but headcount and output will not change. What is strongest?',options:['Call all of it cash saving','Classify it as capacity and test how it can be realized','Delete the benefit without discussion'],answer:1,explanation:'Capacity is not automatic cash, but it may still matter. Avoided hiring, overtime, contractor spend, or additional throughput could change its financial classification.'},
{prompt:'A five-point change in adoption makes the base-case NPV negative. What next?',options:['Present only the base case','Treat adoption as critical uncertainty and test it before rollout','Average downside and upside'],answer:1,explanation:'Sensitivity reveals fragility. A representative pilot, stronger history, or a committed adoption plan could materially change the decision.'},
{prompt:'Operations and finance disagree on time per exception. Which number should the seller use?',options:['The higher estimate','The lower estimate','Preserve both, define the measure, and sample actual cases'],answer:2,explanation:'Choosing either estimate without investigation creates false certainty. A representative time study can resolve the disagreement and reveal variation.'},
{prompt:'The downside case is negative and no implementation owner is committed. What is strongest?',options:['Proceed because the upside is attractive','Investigate, pilot, reduce scope, or stop','Remove the downside from the presentation'],answer:1,explanation:'A full rollout is not justified. A committed owner and evidence that improves the downside threshold could support a different next step.'}
],
'35':[
{prompt:'An enterprise account has massive revenue potential but just signed a 5-year contract with your competitor. What tier should they be?',options:['Tier 1 because of their size','Monitor or Disqualify because propensity is zero','Tier 2 for marketing nurture'],answer:1,explanation:'Potential does not equal propensity. Without a trigger event, pursuing an account locked into a competitor is a massive waste of capacity.'},
{prompt:'You have 50 accounts but only capacity to deeply pursue 5. What is the strongest action?',options:['Send all 50 weekly automated emails','Tier them strictly and focus your time entirely on the top 5','Work longer hours to cover all 50'],answer:1,explanation:'Strategy requires sacrifice. Spreading scarce capacity across 50 accounts guarantees shallow work; focusing on 5 allows for deep, evidence-based account plans.'},
{prompt:'Your account plan hypothesis is "They need better software." What is the primary risk?',options:['It is too long','It is not falsifiable and lacks a specific trigger','The competitor will win on price'],answer:1,explanation:'A hypothesis must be specific and testable. "Better software" does not explain why they must change now, making it impossible to validate.'},
{prompt:'What is the strongest reason to exit an active account pursuit?',options:['They asked for a discount','The opportunity cost exceeds the learning or expected value','They haven\'t replied to one email'],answer:1,explanation:'When an account consumes capacity without yielding progress or evidence, the opportunity cost of ignoring better accounts becomes too high.'}
],
'36':[
{prompt:'A manager loves your product and promises to get it signed, but refuses to introduce you to the CFO. What role are they playing?',options:['Champion','Coach or false champion','Economic buyer'],answer:1,explanation:'A true champion has both the motivation to support you and the influence/willingness to secure access to economic decision-makers.'},
{prompt:'Five users agree they need your software. The security reviewer hasn\'t seen it yet. Do you have consensus?',options:['Yes, majority rules','No, because the security reviewer often has veto power','Yes, if the users complain loudly enough'],answer:1,explanation:'Majority support is not organizational consensus. Missing a stakeholder with veto power (like Security or Legal) usually leads to implementation failure or a blocked deal.'},
{prompt:'You need to present a business case to the VP, but your lower-level contact is defensive about giving you access. What is the strongest response?',options:['Explain that the VP requires an economic review to prevent the project from being rejected later','Go around them and email the VP directly','Ask them to just trust you'],answer:0,explanation:'Explaining how executive involvement reduces risk for the contact makes the introduction mutually beneficial and respectful.'},
{prompt:'Two stakeholders disagree on the primary cause of a workflow problem. What is the best next step?',options:['Side with the more senior stakeholder','Surface the disagreement neutrally and propose a test to find the root cause','Ignore the disagreement and focus on product features'],answer:1,explanation:'Manufacturing false consensus hides the real risk. Surfacing disagreement neutrally allows the group to align on facts before evaluating solutions.'}
],
'37':[
{prompt:'A buyer demands a 20% discount on an enterprise contract. What is the strongest response?',options:['Grant the discount immediately to secure the deal','Exchange price reduction for value-equivalent terms like payment timing or longer commitment','Refuse to negotiate any terms'],answer:1,explanation:'Unconditional discounting destroys margin and signals weak positioning. Price concessions should always be traded for valuable commercial commitments (term, volume, payment terms, or scope).'},
{prompt:'When choosing a pricing value metric, what is the most critical requirement?',options:['It must maximize short-term seller revenue','It must scale with customer value and be reliably measurable','It must match competitors exact pricing structure'],answer:1,explanation:'A strong value metric aligns customer success with seller revenue. If it scales with benefit and is transparent, expansion occurs naturally without friction.'},
{prompt:'A deal has high revenue but negative contribution margin due to custom integration costs. What is strongest?',options:['Close the deal to hit quarterly top-line revenue targets','Restructure packaging/scope or walk away to protect cash flow and margin','Discount implementation fees further to win the logo'],answer:1,explanation:'Top-line revenue that destroys contribution margin damages unit economics and operational capacity. Deals must be qualified for commercial profitability.'},
{prompt:'Why is stated customer willingness-to-pay (WTP) in interviews often unreliable?',options:['Customers always lie intentionally','Stated WTP reflects hypothetical opinion rather than budget-bound behavioral choices','WTP cannot be measured in B2B sales'],answer:1,explanation:'Hypothetical willingness to pay lacks trade-off constraints. Actual purchasing choices, past spend data, and controlled price tests yield far more credible evidence.'}
],
'38':[
{prompt:'An inbound RFP arrives from an enterprise prospect where you have had no prior contact or influence. What is the strongest action?',options:['Submit a full proposal immediately to meet the deadline','Evaluate the RFP using a Bid/No-Bid scorecard and qualify decision access before committing resources','Ask for a 30-day extension without reviewing requirements'],answer:1,explanation:'Unsolicited RFPs without prior contact often serve to benchmark an incumbent. Qualifying via a Bid/No-Bid scorecard prevents wasted pre-sales capacity.'},
{prompt:'During MSA negotiations, the buyer legal team inserts an unlimited liability clause. What is strongest?',options:['Accept the clause to prevent deal slippage','Propose a mutual liability cap tied to 12 months of contract value with fallbacks for specific breaches','Walk away from the deal immediately without discussion'],answer:1,explanation:'Unlimited liability exposes the company to existential risk. Professional contracting uses structured fallbacks (e.g. 1x-2x annual contract value cap) to manage risk responsibly.'},
{prompt:'A prospect requests your security architecture documentation and SOC 2 report. What is strongest?',options:['Refuse to provide security information until the contract is signed','Provide a verified security packet under NDA and route technical questions to qualified owners','Send raw engineering code repositories'],answer:1,explanation:'Security evaluation is a core risk gate in enterprise procurement. Providing verified compliance evidence under NDA establishes trust and accelerates Gate 2 clearance.'},
{prompt:'What is the primary risk of accepting non-standard payment terms (e.g. Net-120) without commercial adjustment?',options:['It increases product usage','It strains working capital and increases credit risk without compensating interest or margin','Legal will automatically reject the contract'],answer:1,explanation:'Extended payment terms act as an interest-free loan to the buyer, straining seller working capital. Extended terms should carry price adjustments or interest penalties.'}
],
'39':[
{prompt:'An AE moves a deal to "Commit" because the champion said "the executive team loves the demo." What is the primary forecast risk?',options:['The deal is under-priced','The stage is based on seller optimism rather than verifiable buyer evidence','The sales cycle is too short'],answer:1,explanation:'Seller statements and verbal compliments are weak forecast indicators. True stage progression requires verifiable buyer actions (e.g. security sign-off, budget allocation, legal review).'},
{prompt:'What is the primary function of a RevOps Stage Dictionary?',options:['To track how many emails AEs send daily','To define explicit entry and exit evidence criteria for each deal stage','To automate pricing calculations'],answer:1,explanation:'A stage dictionary creates a shared, objective standard for pipeline health by replacing subjective opinions with observable buyer evidence criteria.'},
{prompt:'A sales pipeline has 5x quota coverage, but 60% of deals have missed their target close date twice. What is the forecast assessment?',options:['Commit the quota because coverage is high','Haircut the forecast significantly because pipeline aging and slippage signal stalled consensus','Increase the pipeline target to 10x'],answer:1,explanation:'High pipeline coverage is meaningless if deals are stagnant. Repeated close-date slippage indicates broken consensus or missing economic alignment, reducing win probability.'},
{prompt:'How does probabilistic forecast calibration improve sales forecasting over time?',options:['It guarantees 100% win rates on all deals','It compares predicted deal probabilities against actual historical win rates to eliminate forecast bias','It allows AEs to set their own targets'],answer:1,explanation:'Calibration measures forecast accuracy (e.g. using Brier scores) to ensure deals categorized at 70% win probability actually close at ~70% over time.'}
],
'40':[
{prompt:'A software vendor launches a co-sell partnership with an enterprise System Integrator (SI). Which action is most critical to prevent channel conflict?',options:['Offer the SI an exclusive 50% discount on all software licenses','Establish explicit Rules of Engagement with a 90-day deal registration lock and clear house-account boundaries','Allow both direct reps and SI reps to pitch the same account independently'],answer:1,explanation:'Rules of Engagement and timestamped deal registration locks prevent direct and channel reps from competing for the same opportunity, eliminating toxic channel conflict.'},
{prompt:'When evaluating candidate channel partners, why is a high-profile brand logo insufficient evidence of partner fit?',options:['Brand logos are protected by trademark law','Without ICP audience overlap, delivery capability, and joint economics, a famous logo yields zero active deals','Famous partners always demand higher commission splits'],answer:1,explanation:'A famous partner brand without alignment on target buyer ICP, certified technical capability, and mutually profitable economics remains a press-release partnership that produces no revenue.'},
{prompt:'How should a channel manager calculate Partner Contribution Margin for a reseller partner?',options:['Subtract the partner reseller discount and enablement support drag from total contract value plus services attachment','Multiply total pipeline by the partner win rate','Count only the upfront software license discount'],answer:0,explanation:'True partner economics must account for reseller discounts, services margin retention, enablement costs, and ongoing support drag to ensure two-sided profitability.'},
{prompt:'What is the primary objective of requiring work-sample certification for partner pre-sales engineers?',options:['To charge partners mandatory training fees','To verify that partner engineers can execute discovery and technical proof to standards before assigning live deals','To restrict the total number of active partners'],answer:1,explanation:'Certifying demonstrated capability through work-sample evaluations ensures partners deliver high-fidelity customer experiences and protect brand reputation.'}
],
'41':[
{prompt:'Why do structured work-sample interviews outperform unstructured traditional interviews when selecting enterprise sales reps?',options:['Structured work samples take less time to conduct','Work samples evaluate actual job behavior against standard BARS scoring anchors, reducing bias and predicting field performance','Traditional interviews allow candidates to show off their charisma'],answer:1,explanation:'Structured work-sample interviews isolate job-relevant skills (e.g. discovery, business case defense) and evaluate candidates against objective Behaviorally Anchored Rating Scales.'},
{prompt:'An enablement team reports 100% completion of a new product training module, but field win rates remain unchanged. What is the diagnosis?',options:['The sales reps need higher commission incentives','Content completion measures attendance rather than skill transfer to representative work','The product is too expensive'],answer:1,explanation:'LMS content completion is a vanity metric. True enablement requires practice-based training and work-sample certification that transfers to observable field execution.'},
{prompt:'During a single-moment call coaching review, what is the manager\'s primary focus?',options:['Reviewing the entire 60-minute recording and listing 10 different errors','Isolating one key 2-minute decision moment, modeling an alternative, and conducting an immediate roleplay rehearsal','Inspecting the AE\'s quarterly pipeline forecast'],answer:1,explanation:'Effective behavioral coaching focuses on a single observable decision moment, uses self-assessment, models the target behavior, and rehearses execution immediately.'},
{prompt:'A SaaS company offers an uncapped 15% commission on first-year contract value without retention holdbacks. What risk does this create?',options:['Reps will refuse to sign new customers','Reps may discount heavily and sign bad-fit customers who churn quickly, damaging contribution margin','Reps will spend too much time on customer onboarding'],answer:1,explanation:'Incentives without safeguards encourage reps to optimize for short-term commission by closing poor-fit accounts. Adding retention holdbacks or clawbacks aligns rep pay with customer lifetime value.'}
],
'42':[
{prompt:'When selling into international markets, how should sales teams utilize cultural business frameworks?',options:['As rigid character diagnoses to rank the honesty of buyers by nationality','As hypotheses to generate falsifiable questions that are verified locally with specific buyers','To automate pricing discounts based on country GDP'],answer:1,explanation:'Cultural frameworks provide context for inquiry, not deterministic labels. Professional sellers use them to construct questions that verify local decision processes and preferences.'},
{prompt:'During a public-sector RFP quiet period, an AE meets privately with the lead technical evaluator for coffee. What is the consequence?',options:['It accelerates deal closure by building rapport','It violates statutory ex-parte communication rules and can trigger immediate vendor disqualification','It is standard commercial practice in government sales'],answer:1,explanation:'Public procurement laws (such as FAR or EU Directives) mandate strict equal-access rules. Contacting evaluators outside official written channels during quiet periods risks fatal disqualification.'},
{prompt:'When selling software to a healthcare institution subject to HIPAA, what defines the seller\'s compliance boundary?',options:['The seller guarantees 100% legal immunity for all customer data breaches','The seller provides an audit-ready compliance package and BAA for its platform, while the customer remains responsible for internal PHI governance','The seller takes over all clinical operations'],answer:1,explanation:'Compliance is a shared responsibility boundary. Vendors provide audit-certified infrastructure and sign BAAs, but customer data handling remains under buyer governance.'},
{prompt:'Under the U.S. Foreign Corrupt Practices Act (FCPA), what is required when engaging third-party sales agents abroad?',options:['Paying all agent commissions in cash to local bank accounts','Conducting formal beneficial ownership screening, anti-bribery certification, and audit-safe contract terms','Allowing the agent to handle government officials without oversight'],answer:1,explanation:'Companies are legally liable for corrupt acts committed by third-party agents. FCPA compliance mandates rigorous due diligence, PEP screening, written anti-bribery commitments, and transparent fee accounting.'}
]};
