/* Multi-question applied checks for completed depth-edition modules. */
window.SALES_MASTERY.assessments={
'31':[
  {prompt:'During market research for a new SaaS product, 10 target buyers say they "love the concept and would definitely buy it," but none have attempted to solve the problem using existing tools or allocated budget. What is the correct assessment of market demand?',options:['Stated enthusiasm equals confirmed market demand, so building should begin immediately','Hypothetical intention is weak evidence; demand is unproven until buyers demonstrate past behavioral pain or commit resources','The sample size of 10 is too small, so you should survey 500 more people with the same question'],answer:1,explanation:'Hypothetical statements and compliments are weak evidence of fit. True demand requires observable past behavior, active search, or committed capital/time.'},
  {prompt:'An interviewer asks a prospect: "Would an automated document reminder save your team 5 hours a week?" What is the primary flaw in this interview technique?',options:['The question is too short to yield detailed technical requirements','It is a leading, solution-first question that invites politeness rather than uncovering actual past workflow sequence','It should have offered a discount before asking about saved time'],answer:1,explanation:'Leading questions frame the answer and invite polite agreement. Effective customer research anchors in past concrete events ("Walk me through the last time...") to reveal real behavior.'},
  {prompt:'After losing an enterprise deal, the sales rep logs the reason as "lost on price." During an independent post-decision interview, the buyer reveals they chose a competitor because of implementation risk. What does this demonstrate?',options:['Buyers always lie to sales reps about financial constraints','Rep-reported loss reasons are often self-serving deflections; credible win/loss requires independent, open-ended post-decision reviews','The seller should have offered a 30% discount earlier'],answer:1,explanation:'Win/loss data collected by direct sellers frequently defaults to price. Independent reviews reveal structural root causes like consensus breakdown, risk, or implementation fears.'},
  {prompt:'In a research cohort of 10 target accounts, 8 describe a severe workflow bottleneck, while 2 report no issue because they built an internal script. How should the researcher handle the 2 non-conforming accounts?',options:['Discard the 2 accounts as outliers to present a clean 100% problem consensus','Investigate the difference to determine if technical capability or company size defines a specific segment boundary','Force the 2 accounts to adopt the proposed solution anyway'],answer:1,explanation:'Negative cases and non-conforming accounts reveal critical segment boundaries or alternative workarounds, preventing false consensus.'}
],
'32':[
{prompt:'A prospect shows strong web intent but requires a deployment model you cannot support. What is strongest?',options:['Fast-track the opportunity because intent is high','Clarify whether the requirement is mandatory and disqualify if it is','Offer a discount to offset the limitation'],answer:1,explanation:'Intent does not repair poor fit. Clarification and, when necessary, disqualification protect both parties. A supported alternative or a changed requirement could alter the decision.'},
{prompt:'Two groups report the same problem, but one self-serves and the other requires a six-month security process. What should you do?',options:['Keep one segment because the problem is identical','Model them separately because buying process and cost to serve differ','Choose the faster group without further evidence'],answer:1,explanation:'Segments should predict different decisions. Combining them hides motion, proof, and economic differences; speed alone may ignore greater durable value. Retention, margin, and reachable demand could change priority.'},
{prompt:'Buyers praise a differentiator but rarely use it after purchase. What is strongest?',options:['Keep leading with it because interviews were positive','Downgrade the claim until behavior or outcome evidence supports it','Remove the feature immediately'],answer:1,explanation:'Praise is weak evidence of realized value. Downgrading the claim preserves uncertainty without overreacting. If the feature works passively, a better outcome measure could restore the claim.'},
{prompt:'One proposed ICP has high win rate but poor retention. Is it proven?',options:['Yes, acquisition proves fit','No; investigate selection, implementation, margin, and realized value','Yes, if sales cycles are short'],answer:1,explanation:'Win rate measures acquisition, not durable fit. Cohort retention, time-to-value, margin, and causal evidence may support or reject the segment.'}
],
'33':[
{prompt:'A buyer reports a serious problem but has not measured it or assigned an owner. What is strongest?',options:['Push for a decision while concern is high','Propose a small diagnostic action and keep it unqualified','Disqualify immediately in every case'],answer:1,explanation:'A bounded diagnostic tests seriousness without manufacturing urgency. Refusal to investigate or confirmed low consequence could justify disqualification.'},
{prompt:'A contact requests a demo before discussing workflow. Must the seller refuse?',options:['Yes; discovery must always come first','No; clarify evaluation needs and scope a relevant short demo','No; show every feature immediately'],answer:1,explanation:'Respect the request while preventing an unfocused tour. Existing requirements, role, and buying stage determine how much discovery is necessary.'},
{prompt:'Finance and operations offer conflicting causes for the same failure. What belongs in the diagnosis?',options:['The senior stakeholder’s explanation','Both hypotheses, evidence, disagreement, and a test','An average of the two explanations'],answer:1,explanation:'Preserving disagreement prevents invented consensus. A representative sample may show different causes by workflow or segment.'},
{prompt:'Your product fits the symptom but cannot address the confirmed cause. What is strongest?',options:['Reframe the cause around the product','Disclose the limitation and recommend a better path or no sale','Offer a larger discount'],answer:1,explanation:'Disclosure supports an informed decision. New evidence that the product affects a material part of the mechanism could justify reconsideration.'}
],
'34':[
{prompt:'A model converts 3,000 saved hours into €120,000, but headcount and output will not change. What is strongest?',options:['Call all of it cash saving','Classify it as capacity and test how it can be realized','Delete the benefit without discussion'],answer:1,explanation:'Capacity is not automatic cash, but it may still matter. Avoided hiring, overtime, contractor spend, or additional throughput could change its financial classification.'},
{prompt:'A five-point change in adoption makes the base-case NPV negative. What next?',options:['Present only the base case','Treat adoption as critical uncertainty and test it before rollout','Average downside and upside'],answer:1,explanation:'Sensitivity reveals fragility. A representative pilot, stronger history, or a committed adoption plan could materially change the decision.'},
{prompt:'Operations and finance disagree on time per exception. Which number should the seller use?',options:['The higher estimate','The lower estimate','Preserve both, define the measure, and sample actual cases'],answer:2,explanation:'Choosing either estimate without investigation creates false certainty. A representative time study can resolve the disagreement and reveal variation.'},
{prompt:'The downside case is negative and no implementation owner is committed. What is strongest?',options:['Proceed because the upside is attractive','Investigate, pilot, reduce scope, or stop','Remove the downside from the presentation'],answer:1,explanation:'A full rollout is not justified. A committed owner and evidence that improves the downside threshold could support a different next step.'}
],
'35':[
{prompt:'An enterprise account has massive revenue potential but just signed a 5-year contract with your competitor. What tier should they be?',options:['Tier 1 because of their size','Monitor or Disqualify because propensity is zero','Tier 2 for marketing nurture'],answer:1,explanation:'Potential does not equal propensity. Without a trigger event, pursuing an account locked into a competitor is a massive waste of capacity.'},
{prompt:'You have 50 accounts but only capacity to deeply pursue 5. What is the strongest action?',options:['Send all 50 weekly automated emails','Tier them strictly and focus your time entirely on the top 5','Work longer hours to cover all 50'],answer:1,explanation:'Strategy requires sacrifice. Spreading scarce capacity across 50 accounts guarantees shallow work; focusing on 5 allows for deep, evidence-based account plans.'},
{prompt:'Your account plan hypothesis is "They need better software." What is the primary risk?',options:['It is too long','It is not falsifiable and lacks a specific trigger','The competitor will win on price'],answer:1,explanation:'A hypothesis must be specific and testable. "Better software" does not explain why they must change now, making it impossible to validate.'},
{prompt:'What is the strongest reason to exit an active account pursuit?',options:['They asked for a discount','The opportunity cost exceeds the learning or expected value','They haven\'t replied to one email'],answer:1,explanation:'When an account consumes capacity without yielding progress or evidence, the opportunity cost of ignoring better accounts becomes too high.'}
],
'36':[
{prompt:'A manager loves your product and promises to get it signed, but refuses to introduce you to the CFO. What role are they playing?',options:['Champion','Coach or false champion','Economic buyer'],answer:1,explanation:'A true champion has both the motivation to support you and the influence/willingness to secure access to economic decision-makers.'},
{prompt:'Five users agree they need your software. The security reviewer hasn\'t seen it yet. Do you have consensus?',options:['Yes, majority rules','No, because the security reviewer often has veto power','Yes, if the users complain loudly enough'],answer:1,explanation:'Majority support is not organizational consensus. Missing a stakeholder with veto power (like Security or Legal) usually leads to implementation failure or a blocked deal.'},
{prompt:'You need to present a business case to the VP, but your lower-level contact is defensive about giving you access. What is the strongest response?',options:['Explain that the VP requires an economic review to prevent the project from being rejected later','Go around them and email the VP directly','Ask them to just trust you'],answer:0,explanation:'Explaining how executive involvement reduces risk for the contact makes the introduction mutually beneficial and respectful.'},
{prompt:'Two stakeholders disagree on the primary cause of a workflow problem. What is the best next step?',options:['Side with the more senior stakeholder','Surface the disagreement neutrally and propose a test to find the root cause','Ignore the disagreement and focus on product features'],answer:1,explanation:'Manufacturing false consensus hides the real risk. Surfacing disagreement neutrally allows the group to align on facts before evaluating solutions.'}
],
'37':[
{prompt:'A buyer demands a 20% discount on an enterprise contract. What is the strongest response?',options:['Grant the discount immediately to secure the deal','Exchange price reduction for value-equivalent terms like payment timing or longer commitment','Refuse to negotiate any terms'],answer:1,explanation:'Unconditional discounting destroys margin and signals weak positioning. Price concessions should always be traded for valuable commercial commitments (term, volume, payment terms, or scope).'},
{prompt:'When choosing a pricing value metric, what is the most critical requirement?',options:['It must maximize short-term seller revenue','It must scale with customer value and be reliably measurable','It must match competitors exact pricing structure'],answer:1,explanation:'A strong value metric aligns customer success with seller revenue. If it scales with benefit and is transparent, expansion occurs naturally without friction.'},
{prompt:'A deal has high revenue but negative contribution margin due to custom integration costs. What is strongest?',options:['Close the deal to hit quarterly top-line revenue targets','Restructure packaging/scope or walk away to protect cash flow and margin','Discount implementation fees further to win the logo'],answer:1,explanation:'Top-line revenue that destroys contribution margin damages unit economics and operational capacity. Deals must be qualified for commercial profitability.'},
{prompt:'Why is stated customer willingness-to-pay (WTP) in interviews often unreliable?',options:['Customers always lie intentionally','Stated WTP reflects hypothetical opinion rather than budget-bound behavioral choices','WTP cannot be measured in B2B sales'],answer:1,explanation:'Hypothetical willingness to pay lacks trade-off constraints. Actual purchasing choices, past spend data, and controlled price tests yield far more credible evidence.'}
],
'38':[
{prompt:'An inbound RFP arrives from an enterprise prospect where you have had no prior contact or influence. What is the strongest action?',options:['Submit a full proposal immediately to meet the deadline','Evaluate the RFP using a Bid/No-Bid scorecard and qualify decision access before committing resources','Ask for a 30-day extension without reviewing requirements'],answer:1,explanation:'Unsolicited RFPs without prior contact often serve to benchmark an incumbent. Qualifying via a Bid/No-Bid scorecard prevents wasted pre-sales capacity.'},
{prompt:'During MSA negotiations, the buyer legal team inserts an unlimited liability clause. What is strongest?',options:['Accept the clause to prevent deal slippage','Propose a mutual liability cap tied to 12 months of contract value with fallbacks for specific breaches','Walk away from the deal immediately without discussion'],answer:1,explanation:'Unlimited liability exposes the company to existential risk. Professional contracting uses structured fallbacks (e.g. 1x-2x annual contract value cap) to manage risk responsibly.'},
{prompt:'A prospect requests your security architecture documentation and SOC 2 report. What is strongest?',options:['Refuse to provide security information until the contract is signed','Provide a verified security packet under NDA and route technical questions to qualified owners','Send raw engineering code repositories'],answer:1,explanation:'Security evaluation is a core risk gate in enterprise procurement. Providing verified compliance evidence under NDA establishes trust and accelerates Gate 2 clearance.'},
{prompt:'What is the primary risk of accepting non-standard payment terms (e.g. Net-120) without commercial adjustment?',options:['It increases product usage','It strains working capital and increases credit risk without compensating interest or margin','Legal will automatically reject the contract'],answer:1,explanation:'Extended payment terms act as an interest-free loan to the buyer, straining seller working capital. Extended terms should carry price adjustments or interest penalties.'}
],
'39':[
{prompt:'An AE moves a deal to "Commit" because the champion said "the executive team loves the demo." What is the primary forecast risk?',options:['The deal is under-priced','The stage is based on seller optimism rather than verifiable buyer evidence','The sales cycle is too short'],answer:1,explanation:'Seller statements and verbal compliments are weak forecast indicators. True stage progression requires verifiable buyer actions (e.g. security sign-off, budget allocation, legal review).'},
{prompt:'What is the primary function of a RevOps Stage Dictionary?',options:['To track how many emails AEs send daily','To define explicit entry and exit evidence criteria for each deal stage','To automate pricing calculations'],answer:1,explanation:'A stage dictionary creates a shared, objective standard for pipeline health by replacing subjective opinions with observable buyer evidence criteria.'},
{prompt:'A sales pipeline has 5x quota coverage, but 60% of deals have missed their target close date twice. What is the forecast assessment?',options:['Commit the quota because coverage is high','Haircut the forecast significantly because pipeline aging and slippage signal stalled consensus','Increase the pipeline target to 10x'],answer:1,explanation:'High pipeline coverage is meaningless if deals are stagnant. Repeated close-date slippage indicates broken consensus or missing economic alignment, reducing win probability.'},
{prompt:'How does probabilistic forecast calibration improve sales forecasting over time?',options:['It guarantees 100% win rates on all deals','It compares predicted deal probabilities against actual historical win rates to eliminate forecast bias','It allows AEs to set their own targets'],answer:1,explanation:'Calibration measures forecast accuracy (e.g. using Brier scores) to ensure deals categorized at 70% win probability actually close at ~70% over time.'}
],
'40':[
{prompt:'A software vendor launches a co-sell partnership with an enterprise System Integrator (SI). Which action is most critical to prevent channel conflict?',options:['Offer the SI an exclusive 50% discount on all software licenses','Establish explicit Rules of Engagement with a 90-day deal registration lock and clear house-account boundaries','Allow both direct reps and SI reps to pitch the same account independently'],answer:1,explanation:'Rules of Engagement and timestamped deal registration locks prevent direct and channel reps from competing for the same opportunity, eliminating toxic channel conflict.'},
{prompt:'When evaluating candidate channel partners, why is a high-profile brand logo insufficient evidence of partner fit?',options:['Brand logos are protected by trademark law','Without ICP audience overlap, delivery capability, and joint economics, a famous logo yields zero active deals','Famous partners always demand higher commission splits'],answer:1,explanation:'A famous partner brand without alignment on target buyer ICP, certified technical capability, and mutually profitable economics remains a press-release partnership that produces no revenue.'},
{prompt:'How should a channel manager calculate Partner Contribution Margin for a reseller partner?',options:['Subtract the partner reseller discount and enablement support drag from total contract value plus services attachment','Multiply total pipeline by the partner win rate','Count only the upfront software license discount'],answer:0,explanation:'True partner economics must account for reseller discounts, services margin retention, enablement costs, and ongoing support drag to ensure two-sided profitability.'},
{prompt:'What is the primary objective of requiring work-sample certification for partner pre-sales engineers?',options:['To charge partners mandatory training fees','To verify that partner engineers can execute discovery and technical proof to standards before assigning live deals','To restrict the total number of active partners'],answer:1,explanation:'Certifying demonstrated capability through work-sample evaluations ensures partners deliver high-fidelity customer experiences and protect brand reputation.'}
],
'41':[
{prompt:'Why do structured work-sample interviews outperform unstructured traditional interviews when selecting enterprise sales reps?',options:['Structured work samples take less time to conduct','Work samples evaluate actual job behavior against standard BARS scoring anchors, reducing bias and predicting field performance','Traditional interviews allow candidates to show off their charisma'],answer:1,explanation:'Structured work-sample interviews isolate job-relevant skills (e.g. discovery, business case defense) and evaluate candidates against objective Behaviorally Anchored Rating Scales.'},
{prompt:'An enablement team reports 100% completion of a new product training module, but field win rates remain unchanged. What is the diagnosis?',options:['The sales reps need higher commission incentives','Content completion measures attendance rather than skill transfer to representative work','The product is too expensive'],answer:1,explanation:'LMS content completion is a vanity metric. True enablement requires practice-based training and work-sample certification that transfers to observable field execution.'},
{prompt:'During a single-moment call coaching review, what is the manager\'s primary focus?',options:['Reviewing the entire 60-minute recording and listing 10 different errors','Isolating one key 2-minute decision moment, modeling an alternative, and conducting an immediate roleplay rehearsal','Inspecting the AE\'s quarterly pipeline forecast'],answer:1,explanation:'Effective behavioral coaching focuses on a single observable decision moment, uses self-assessment, models the target behavior, and rehearses execution immediately.'},
{prompt:'A SaaS company offers an uncapped 15% commission on first-year contract value without retention holdbacks. What risk does this create?',options:['Reps will refuse to sign new customers','Reps may discount heavily and sign bad-fit customers who churn quickly, damaging contribution margin','Reps will spend too much time on customer onboarding'],answer:1,explanation:'Incentives without safeguards encourage reps to optimize for short-term commission by closing poor-fit accounts. Adding retention holdbacks or clawbacks aligns rep pay with customer lifetime value.'}
],
'42':[
{prompt:'When selling into international markets, how should sales teams utilize cultural business frameworks?',options:['As rigid character diagnoses to rank the honesty of buyers by nationality','As hypotheses to generate falsifiable questions that are verified locally with specific buyers','To automate pricing discounts based on country GDP'],answer:1,explanation:'Cultural frameworks provide context for inquiry, not deterministic labels. Professional sellers use them to construct questions that verify local decision processes and preferences.'},
{prompt:'During a public-sector RFP quiet period, an AE meets privately with the lead technical evaluator for coffee. What is the consequence?',options:['It accelerates deal closure by building rapport','It violates statutory ex-parte communication rules and can trigger immediate vendor disqualification','It is standard commercial practice in government sales'],answer:1,explanation:'Public procurement laws (such as FAR or EU Directives) mandate strict equal-access rules. Contacting evaluators outside official written channels during quiet periods risks fatal disqualification.'},
{prompt:'When selling software to a healthcare institution subject to HIPAA, what defines the seller\'s compliance boundary?',options:['The seller guarantees 100% legal immunity for all customer data breaches','The seller provides an audit-ready compliance package and BAA for its platform, while the customer remains responsible for internal PHI governance','The seller takes over all clinical operations'],answer:1,explanation:'Compliance is a shared responsibility boundary. Vendors provide audit-certified infrastructure and sign BAAs, but customer data handling remains under buyer governance.'},
{prompt:'Under the U.S. Foreign Corrupt Practices Act (FCPA), what is required when engaging third-party sales agents abroad?',options:['Paying all agent commissions in cash to local bank accounts','Conducting formal beneficial ownership screening, anti-bribery certification, and audit-safe contract terms','Allowing the agent to handle government officials without oversight'],answer:1,explanation:'Companies are legally liable for corrupt acts committed by third-party agents. FCPA compliance mandates rigorous due diligence, PEP screening, written anti-bribery commitments, and transparent fee accounting.'}
]};
